package com.bowoon.model

data class People(
    val adult: Boolean? = null,
    val alsoKnownAs: List<String>? = null,
    val biography: String? = null,
    val birthday: String? = null,
    val combineCredits: CombineCredits? = null,
    val deathday: String? = null,
    val externalIds: ExternalIds? = null,
    val gender: Int? = null,
    val homepage: String? = null,
    override val id: Int? = null,
    val images: List<Image>? = null,
    val imdbId: String? = null,
    val knownForDepartment: String? = null,
    override val title: String? = null,
    override val originalTitle: String? = null,
    val placeOfBirth: String? = null,
    val popularity: Double? = null,
    override val posterPath: String? = null,
    override val genres: List<Genre>? = null,
    override val releaseDate: String? = null
) : Media

data class RelatedMovie(
    val adult: Boolean? = null,
    val backdropPath: String? = null,
    val character: String? = null,
    val creditId: String? = null,
    val episodeCount: Int? = null,
    val firstAirDate: String? = null,
    val genreIds: List<Int>? = null,
    val id: Int? = null,
    val mediaType: String? = null,
    val name: String? = null,
    val order: Int? = null,
    val originCountry: List<String>? = null,
    val originalLanguage: String? = null,
    val originalName: String? = null,
    val originalTitle: String? = null,
    val overview: String? = null,
    val popularity: Double? = null,
    val posterPath: String? = null,
    val releaseDate: String? = null,
    val title: String? = null,
    val video: Boolean? = null,
    val voteAverage: Double? = null,
    val voteCount: Int? = null,
    val department: String? = null,
    val job: String? = null,
)