name: App build

on:
  schedule:
    - cron: "30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      KEY_STORE_ENCRYPT: ${{ secrets.KEY_STORE_ENCRYPT }}
      GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
          ref: develop
      - name: Grant Permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      - name: Create sign folder
        run: mkdir -p ./sign
      - name: Decode And Save Keystore Base64
        run: |
          echo "$KEY_STORE_ENCRYPT" | base64 -i --decode > ./sign/bowoon.jks
      - name: Create local.properties
        run: |
          echo "$LOCAL_PROPERTIES" > ./sign/local.properties
      - name: Create google-services.json
        run: |
          echo "$GOOGLE_SERVICES_JSON" > ./app/google-services.json
      - name: build release
        run: ./gradlew assembleProdRelease
